# Generated by Django 4.1 on 2022-10-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_model_title', models.CharField(max_length=200)),
                ('test_model_content', models.TextField()),
                ('test_model_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
