# Generated by Django 4.1 on 2022-10-30 10:32

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_model_title', models.CharField(max_length=200)),
                ('test_model_content', models.TextField()),
                ('test_model_additional', tinymce.models.HTMLField(default=None)),
                ('test_model_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
            options={
                'verbose_name_plural': 'TestModels',
            },
        ),
    ]
