# Generated by Django 4.1.2 on 2022-11-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_asset_assetcategory_comment_news_favourite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="last_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="assetcategory",
            name="category_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
