# Generated by Django 4.1 on 2022-10-29 07:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_testmodel_test_model_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='test_model_additional',
            field=tinymce.models.HTMLField(default=None),
        ),
    ]
