# Generated by Django 4.1 on 2022-10-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testmodel_test_model_additional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={'verbose_name_plural': 'TestModels'},
        ),
    ]
