# Generated by Django 4.1.2 on 2022-11-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_asset_asset_name_alter_asset_asset_ticker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="photo_link",
            field=models.URLField(blank=True, default=None),
        ),
    ]
