# Generated by Django 4.1.2 on 2022-11-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_asset_photo_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="market_size",
            field=models.FloatField(default=0),
        ),
    ]
