# Generated by Django 4.1.2 on 2022-11-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_asset_asset_name_alter_asset_photo_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcategory",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
