# Generated by Django 4.1.2 on 2022-11-14 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_assetcategory_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="link",
            new_name="href",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="source",
            new_name="publisher",
        ),
        migrations.AddField(
            model_name="news",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="date_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="published date"
            ),
        ),
    ]
