# Generated by Django 4.1.2 on 2022-11-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_rename_link_news_href_rename_source_news_publisher_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="date_time",
            new_name="published_date",
        ),
    ]
