# Generated by Django 4.1.2 on 2022-11-19 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0012_rename_href_news_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="price time"
                    ),
                ),
                ("price", models.FloatField(default=0)),
                ("volume", models.FloatField(default=0)),
                (
                    "asset",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.asset",
                        verbose_name="Asset",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "AssetPrices",
            },
        ),
        migrations.CreateModel(
            name="FavouriteAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favourite_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date added"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.asset",
                        verbose_name="Asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "FavouriteAssets",
            },
        ),
        migrations.CreateModel(
            name="FavouriteCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favourite_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date added"
                    ),
                ),
                (
                    "asset_category",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="main.assetcategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "FavouriteCategories",
            },
        ),
        migrations.RemoveField(
            model_name="favourite",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="favourite",
            name="user",
        ),
        migrations.DeleteModel(
            name="TestModel",
        ),
        migrations.DeleteModel(
            name="favourite",
        ),
        migrations.AddConstraint(
            model_name="assetprice",
            constraint=models.UniqueConstraint(
                fields=("asset", "date_time"), name="unique_asset_date"
            ),
        ),
    ]
