# Generated by Django 4.1.2 on 2022-11-19 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0013_assetprice_favouriteasset_favouritecategory_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentlike",
            options={"verbose_name_plural": "Commentlikes"},
        ),
        migrations.AlterField(
            model_name="commentlike",
            name="comment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.comment",
                verbose_name="Comment",
            ),
        ),
        migrations.AlterField(
            model_name="commentlike",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
