# Generated by Django 4.1.2 on 2022-11-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_commentlike_options_alter_commentlike_comment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assetprice",
            options={
                "get_latest_by": "date_time",
                "verbose_name_plural": "AssetPrices",
            },
        ),
    ]
