# Generated by Django 4.1.2 on 2022-11-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_assetprice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="liked_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assetcategory",
            name="liked_count",
            field=models.IntegerField(default=0),
        ),
    ]
