# Generated by Django 4.1.2 on 2022-11-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_asset_liked_count_assetcategory_liked_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news", old_name="description", new_name="summary",
        ),
        migrations.AddField(
            model_name="news",
            name="thumbnail",
            field=models.URLField(default=None, null=True),
        ),
    ]
