# Generated by Django 4.1.2 on 2022-11-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_news_mentioned_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_count',
        ),
        migrations.AlterField(
            model_name='news',
            name='mentioned_asset',
            field=models.ManyToManyField(blank=True, related_name='mentioned_asset', to='main.asset'),
        ),
    ]
