# Generated by Django 4.1.2 on 2022-11-29 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_remove_comment_like_count_alter_news_mentioned_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
