# Generated by Django 4.1.2 on 2022-11-29 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_comment_liked_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetcategory',
            old_name='liked_count',
            new_name='like_count',
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='liked_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
