# Generated by Django 4.1.2 on 2022-11-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_liked_count_assetcategory_like_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouriteasset',
            options={'get_latest_by': 'favourite_date', 'verbose_name_plural': 'FavouriteAssets'},
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='liked_count',
            new_name='like_count',
        ),
        migrations.AddConstraint(
            model_name='favouriteasset',
            constraint=models.UniqueConstraint(fields=('asset', 'user'), name='unique_asset_user'),
        ),
    ]
