# Generated by Django 4.1.2 on 2022-11-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_favouriteasset_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='like_count',
            new_name='favourite_count',
        ),
        migrations.RenameField(
            model_name='assetcategory',
            old_name='like_count',
            new_name='favourite_count',
        ),
        migrations.RemoveField(
            model_name='assetcategory',
            name='liked_users',
        ),
    ]
