# Generated by Django 4.1.2 on 2022-11-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_remove_asset_favourite_count_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news", old_name="description", new_name="summary",
        ),
        migrations.AddField(
            model_name="news",
            name="thumbnail",
            field=models.URLField(default=None, null=True),
        ),
    ]
