# Generated by Django 4.1.2 on 2022-12-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_description_news_summary_news_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='popularity',
            field=models.FloatField(default=0),
        ),
    ]
