# Generated by Django 4.1.2 on 2022-12-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_asset_popularity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='mentioned_asset',
            new_name='mentioned_assets',
        ),
    ]
