# Generated by Django 4.1.2 on 2022-12-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_price_assetprice_open_assetprice_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='child_count',
            field=models.FloatField(default=0),
        ),
    ]
