# Generated by Django 4.1.2 on 2023-01-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_comment_child_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="follower_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="child_count",
            field=models.IntegerField(default=0),
        ),
    ]
