STOCK_TICKERS_LIST = ["MMM" ,
"AOS" ,
"ABT" ,
"ABBV" ,
"ABMD" ,
"ACN" ,
"ATVI" ,
"ADM" ,
"ADBE" ,
"ADP" ,
"AAP" ,
"AES" ,
"AFL" ,
"A" ,
"APD" ,
"AKAM" ,
"ALK" ,
"ALB" ,
"ARE" ,
"ALGN" ,
"ALLE" ,
"LNT" ,
"ALL" ,
"GOOGL" ,
"GOOG" ,
"MO" ,
"AMZN" ,
"AMCR" ,
"AMD" ,
"AEE" ,
"AAL" ,
"AEP" ,
"AXP" ,
"AIG" ,
"AMT" ,
"AWK" ,
"AMP" ,
"ABC" ,
"AME" ,
"AMGN" ,
"APH" ,
"ADI" ,
"ANSS" ,
"AON" ,
"APA" ,
"AAPL" ,
"AMAT" ,
"APTV" ,
"ANET" ,
"AJG" ,
"AIZ" ,
"T" ,
"ATO" ,
"ADSK" ,
"AZO" ,
"AVB" ,
"AVY" ,
"BKR" ,
"BALL" ,
"BAC" ,
"BBWI" ,
"BAX" ,
"BDX" ,
"WRB" ,
"BRK-B" ,
"BBY" ,
"BIO" ,
"TECH" ,
"BIIB" ,
"BLK" ,
"BK" ,
"BA" ,
"BKNG" ,
"BWA" ,
"BXP" ,
"BSX" ,
"BMY" ,
"AVGO" ,
"BR" ,
"BRO" ,
"BF-B" ,
"CHRW" ,
"CDNS" ,
"CZR" ,
"CPT" ,
"CPB" ,
"COF" ,
"CAH" ,
"KMX" ,
"CCL" ,
"CARR" ,
"CTLT" ,
"CAT" ,
"CBOE" ,
"CBRE" ,
"CDW" ,
"CE" ,
"CNC" ,
"CNP" ,
"CDAY" ,
"CF" ,
"CRL" ,
"SCHW" ,
"CHTR" ,
"CVX" ,
"CMG" ,
"CB" ,
"CHD" ,
"CI" ,
"CINF" ,
"CTAS" ,
"CSCO" ,
"C" ,
"CFG" ,
"CLX" ,
"CME" ,
"CMS" ,
"KO" ,
"CTSH" ,
"CL" ,
"CMCSA" ,
"CMA" ,
"CAG" ,
"COP" ,
"ED" ,
"STZ" ,
"CEG" ,
"COO" ,
"CPRT" ,
"GLW" ,
"CTVA" ,
"CSGP" ,
"COST" ,
"CTRA" ,
"CCI" ,
"CSX" ,
"CMI" ,
"CVS" ,
"DHI" ,
"DHR" ,
"DRI" ,
"DVA" ,
"DE" ,
"DAL" ,
"XRAY" ,
"DVN" ,
"DXCM" ,
"FANG" ,
"DLR" ,
"DFS" ,
"DISH" ,
"DIS" ,
"DG" ,
"DLTR" ,
"D" ,
"DPZ" ,
"DOV" ,
"DOW" ,
"DTE" ,
"DUK" ,
"DD" ,
"DXC" ,
"EMN" ,
"ETN" ,
"EBAY" ,
"ECL" ,
"EIX" ,
"EW" ,
"EA" ,
"ELV" ,
"LLY" ,
"EMR" ,
"ENPH" ,
"ETR" ,
"EOG" ,
"EPAM" ,
"EQT" ,
"EFX" ,
"EQIX" ,
"EQR" ,
"ESS" ,
"EL" ,
"ETSY" ,
"RE" ,
"EVRG" ,
"ES" ,
"EXC" ,
"EXPE" ,
"EXPD" ,
"EXR" ,
"XOM" ,
"FFIV" ,
"FDS" ,
"FAST" ,
"FRT" ,
"FDX" ,
"FITB" ,
"FRC" ,
"FE" ,
"FIS" ,
"FISV" ,
"FLT" ,
"FMC" ,
"F" ,
"FTNT" ,
"FTV" ,
"FBHS" ,
"FOXA" ,
"FOX" ,
"BEN" ,
"FCX" ,
"GRMN" ,
"IT" ,
"GNRC" ,
"GD" ,
"GE" ,
"GIS" ,
"GM" ,
"GPC" ,
"GILD" ,
"GL" ,
"GPN" ,
"GS" ,
"HAL" ,
"HIG" ,
"HAS" ,
"HCA" ,
"PEAK" ,
"HSIC" ,
"HSY" ,
"HES" ,
"HPE" ,
"HLT" ,
"HOLX" ,
"HD" ,
"HON" ,
"HRL" ,
"HST" ,
"HWM" ,
"HPQ" ,
"HUM" ,
"HBAN" ,
"HII" ,
"IBM" ,
"IEX" ,
"IDXX" ,
"ITW" ,
"ILMN" ,
"INCY" ,
"IR" ,
"INTC" ,
"ICE" ,
"IP" ,
"IPG" ,
"IFF" ,
"INTU" ,
"ISRG" ,
"IVZ" ,
"INVH" ,
"IQV" ,
"IRM" ,
"JBHT" ,
"JKHY" ,
"J" ,
"JNJ" ,
"JCI" ,
"JPM" ,
"JNPR" ,
"K" ,
"KDP" ,
"KEY" ,
"KEYS" ,
"KMB" ,
"KIM" ,
"KMI" ,
"KLAC" ,
"KHC" ,
"KR" ,
"LHX" ,
"LH" ,
"LRCX" ,
"LW" ,
"LVS" ,
"LDOS" ,
"LEN" ,
"LNC" ,
"LIN" ,
"LYV" ,
"LKQ" ,
"LMT" ,
"L" ,
"LOW" ,
"LUMN" ,
"LYB" ,
"MTB" ,
"MRO" ,
"MPC" ,
"MKTX" ,
"MAR" ,
"MMC" ,
"MLM" ,
"MAS" ,
"MA" ,
"MTCH" ,
"MKC" ,
"MCD" ,
"MCK" ,
"MDT" ,
"MRK" ,
"META" ,
"MET" ,
"MTD" ,
"MGM" ,
"MCHP" ,
"MU" ,
"MSFT" ,
"MAA" ,
"MRNA" ,
"MHK" ,
"MOH" ,
"TAP" ,
"MDLZ" ,
"MPWR" ,
"MNST" ,
"MCO" ,
"MS" ,
"MOS" ,
"MSI" ,
"MSCI" ,
"NDAQ" ,
"NTAP" ,
"NFLX" ,
"NWL" ,
"NEM" ,
"NWSA" ,
"NWS" ,
"NEE" ,
"NKE" ,
"NI" ,
"NDSN" ,
"NSC" ,
"NTRS" ,
"NOC" ,
"NLOK" ,
"NCLH" ,
"NRG" ,
"NUE" ,
"NVDA" ,
"NVR" ,
"NXPI" ,
"ORLY" ,
"OXY" ,
"ODFL" ,
"OMC" ,
"ON" ,
"OKE" ,
"ORCL" ,
"OGN" ,
"OTIS" ,
"PCAR" ,
"PKG" ,
"PARA" ,
"PH" ,
"PAYX" ,
"PAYC" ,
"PYPL" ,
"PNR" ,
"PEP" ,
"PKI" ,
"PFE" ,
"PCG" ,
"PM" ,
"PSX" ,
"PNW" ,
"PXD" ,
"PNC" ,
"POOL" ,
"PPG" ,
"PPL" ,
"PFG" ,
"PG" ,
"PGR" ,
"PLD" ,
"PRU" ,
"PEG" ,
"PTC" ,
"PSA" ,
"PHM" ,
"QRVO" ,
"PWR" ,
"QCOM" ,
"DGX" ,
"RL" ,
"RJF" ,
"RTX" ,
"O" ,
"REG" ,
"REGN" ,
"RF" ,
"RSG" ,
"RMD" ,
"RHI" ,
"ROK" ,
"ROL" ,
"ROP" ,
"ROST" ,
"RCL" ,
"SPGI" ,
"CRM" ,
"SBAC" ,
"SLB" ,
"STX" ,
"SEE" ,
"SRE" ,
"NOW" ,
"SHW" ,
"SBNY" ,
"SPG" ,
"SWKS" ,
"SJM" ,
"SNA" ,
"SEDG" ,
"SO" ,
"LUV" ,
"SWK" ,
"SBUX" ,
"STT" ,
"STE" ,
"SYK" ,
"SIVB" ,
"SYF" ,
"SNPS" ,
"SYY" ,
"TMUS" ,
"TROW" ,
"TTWO" ,
"TPR" ,
"TRGP" ,
"TGT" ,
"TEL" ,
"TDY" ,
"TFX" ,
"TER" ,
"TSLA" ,
"TXN" ,
"TXT" ,
"TMO" ,
"TJX" ,
"TSCO" ,
"TT" ,
"TDG" ,
"TRV" ,
"TRMB" ,
"TFC" ,
"TWTR" ,
"TYL" ,
"TSN" ,
"USB" ,
"UDR" ,
"ULTA" ,
"UNP" ,
"UAL" ,
"UPS" ,
"URI" ,
"UNH" ,
"UHS" ,
"VLO" ,
"VTR" ,
"VRSN" ,
"VRSK" ,
"VZ" ,
"VRTX" ,
"VFC" ,
"VTRS" ,
"VICI" ,
"V" ,
"VNO" ,
"VMC" ,
"WAB" ,
"WBA" ,
"WMT" ,
"WBD" ,
"WM" ,
"WAT" ,
"WEC" ,
"WFC" ,
"WELL" ,
"WST" ,
"WDC" ,
"WRK" ,
"WY" ,
"WHR" ,
"WMB" ,
"WTW" ,
"GWW" ,
"WYNN" ,
"XEL" ,
"XYL" ,
"YUM" ,
"ZBRA" ,
"ZBH" ,
"ZION" ,
"ZTS"]

STOCKS_LIST = ['3M Company',
 'A.O. Smith Corporation',
 'Abbott Laboratories',
 'AbbVie Inc.',
 'ABIOMED, Inc.',
 'Accenture plc',
 'Activision Blizzard, Inc',
 'Archer-Daniels-Midland Company',
 'Adobe Inc.',
 'Automatic Data Processing, Inc.',
 'Advance Auto Parts Inc.',
 'The AES Corporation',
 'AFLAC Incorporated',
 'Agilent Technologies, Inc.',
 'Air Products and Chemicals, Inc',
 'Akamai Technologies, Inc.',
 'Alaska Air Group, Inc.',
 'Albemarle Corporation',
 'Alexandria Real Estate Equities',
 'Align Technology, Inc.',
 'Allegion plc',
 'Alliant Energy Corporation',
 'Allstate Corporation (The)',
 'Alphabet Inc.',
 'Alphabet Inc.',
 'Altria Group, Inc.',
 'Amazon.com, Inc.',
 'Amcor plc',
 'Advanced Micro Devices, Inc.',
 'Ameren Corporation',
 'American Airlines Group, Inc.',
 'American Electric Power Company',
 'American Express Company',
 'American International Group, I',
 'American Tower Corporation (REI',
 'American Water Works Company, I',
 'Ameriprise Financial, Inc.',
 'AmerisourceBergen Corporation',
 'AMETEK, Inc.',
 'Amgen Inc.',
 'Amphenol Corporation',
 'Analog Devices, Inc.',
 'ANSYS, Inc.',
 'Aon plc',
 'APA Corporation',
 'Apple Inc.',
 'Applied Materials, Inc.',
 'Aptiv PLC',
 'Arista Networks, Inc.',
 'Arthur J. Gallagher & Co.',
 'Assurant, Inc.',
 'AT&T Inc.',
 'Atmos Energy Corporation',
 'Autodesk, Inc.',
 'AutoZone, Inc.',
 'AvalonBay Communities, Inc.',
 'Avery Dennison Corporation',
 'Baker Hughes Company',
 'Ball Corporation',
 'Bank of America Corporation',
 'Bath & Body Works, Inc.',
 'Baxter International Inc.',
 'Becton, Dickinson and Company',
 'W.R. Berkley Corporation',
 'Berkshire Hathaway Inc Class B',
 'Best Buy Co., Inc.',
 'Bio-Rad Laboratories, Inc.',
 'Bio-Techne Corp',
 'Biogen Inc.',
 'BlackRock, Inc.',
 'The Bank of New York Mellon Cor',
 'Boeing Company (The)',
 'Booking Holdings Inc. Common St',
 'BorgWarner Inc.',
 'Boston Properties, Inc.',
 'Boston Scientific Corporation',
 'Bristol-Myers Squibb Company',
 'Broadcom Inc.',
 'Broadridge Financial Solutions,',
 'Brown & Brown, Inc.',
 'Brown-Forman Corporation Class B',
 'C.H. Robinson Worldwide, Inc.',
 'Cadence Design Systems, Inc.',
 'Caesars Entertainment, Inc.',
 'Camden Property Trust',
 'Campbell Soup Company',
 'Capital One Financial Corporati',
 'Cardinal Health, Inc.',
 'CarMax Inc',
 'Carnival Corporation',
 'Carrier Global Corporation',
 'Catalent, Inc.',
 'Caterpillar, Inc.',
 'Cboe Global Markets, Inc.',
 'CBRE Group Inc',
 'CDW Corporation',
 'Celanese Corporation Celanese C',
 'Centene Corporation',
 'CenterPoint Energy, Inc (Holdin',
 'Ceridian HCM Holding Inc.',
 'CF Industries Holdings, Inc.',
 'Charles River Laboratories Inte',
 'Charles Schwab Corporation (The',
 'Charter Communications, Inc.',
 'Chevron Corporation',
 'Chipotle Mexican Grill, Inc.',
 'Chubb Limited',
 'Church & Dwight Company, Inc.',
 'Cigna Corporation',
 'Cincinnati Financial Corporatio',
 'Cintas Corporation',
 'Cisco Systems, Inc.',
 'Citigroup, Inc.',
 'Citizens Financial Group, Inc.',
 'Clorox Company (The)',
 'CME Group Inc.',
 'CMS Energy Corporation',
 'Coca-Cola Company (The)',
 'Cognizant Technology Solutions ',
 'Colgate-Palmolive Company',
 'Comcast Corporation',
 'Comerica Incorporated',
 'ConAgra Brands, Inc.',
 'ConocoPhillips',
 'Consolidated Edison, Inc.',
 'Constellation Brands, Inc.',
 'Constellation Energy Corporatio',
 'The Cooper Companies, Inc.',
 'Copart, Inc.',
 'Corning Incorporated',
 'Corteva, Inc.',
 'CoStar Group, Inc.',
 'Costco Wholesale Corporation',
 'Coterra Energy Inc.',
 'Crown Castle Inc.',
 'CSX Corporation',
 'Cummins Inc.',
 'CVS Health Corporation',
 'D.R. Horton, Inc.',
 'Danaher Corporation',
 'Darden Restaurants, Inc.',
 'DaVita Inc.',
 'Deere & Company',
 'Delta Air Lines, Inc.',
 'DENTSPLY SIRONA Inc.',
 'Devon Energy Corporation',
 'DexCom, Inc.',
 'Diamondback Energy, Inc.',
 'Digital Realty Trust, Inc.',
 'Discover Financial Services',
 'DISH Network Corporation',
 'Walt Disney Company (The)',
 'Dollar General Corporation',
 'Dollar Tree, Inc.',
 'Dominion Energy, Inc.',
 "Domino's Pizza Inc",
 'Dover Corporation',
 'Dow Inc.',
 'DTE Energy Company',
 'Duke Energy Corporation (Holdin',
 'DuPont de Nemours, Inc.',
 'DXC Technology Company',
 'Eastman Chemical Company',
 'Eaton Corporation, PLC',
 'eBay Inc.',
 'Ecolab Inc.',
 'Edison International',
 'Edwards Lifesciences Corporatio',
 'Electronic Arts Inc.',
 'Elevance Health, Inc.',
 'Eli Lilly and Company',
 'Emerson Electric Company',
 'Enphase Energy, Inc.',
 'Entergy Corporation',
 'EOG Resources, Inc.',
 'EPAM Systems, Inc.',
 'EQT Corporation',
 'Equifax, Inc.',
 'Equinix, Inc.',
 'Equity Residential',
 'Essex Property Trust, Inc.',
 'Estee Lauder Companies, Inc. (T',
 'Etsy, Inc.',
 'Everest Re Group, Ltd.',
 'Evergy, Inc.',
 'Eversource Energy (D/B/A)',
 'Exelon Corporation',
 'Expedia Group, Inc.',
 'Expeditors International of Was',
 'Extra Space Storage Inc',
 'Exxon Mobil Corporation',
 'F5, Inc.',
 'FactSet Research Systems Inc.',
 'Fastenal Company',
 'Federal Realty Investment Trust',
 'FedEx Corporation',
 'Fifth Third Bancorp',
 'FIRST REPUBLIC BANK',
 'FirstEnergy Corp.',
 'Fidelity National Information S',
 'Fiserv, Inc.',
 'FleetCor Technologies, Inc.',
 'FMC Corporation',
 'Ford Motor Company',
 'Fortinet, Inc.',
 'Fortive Corporation',
 'Fortune Brands Home & Security,',
 'Fox Corporation',
 'Fox Corporation',
 'Franklin Resources, Inc.',
 'Freeport-McMoRan, Inc.',
 'Garmin Ltd.',
 'Gartner, Inc.',
 'Generac Holdlings Inc.',
 'General Dynamics Corporation',
 'General Electric Company',
 'General Mills, Inc.',
 'General Motors Company',
 'Genuine Parts Company',
 'Gilead Sciences, Inc.',
 'Globe Life Inc.',
 'Global Payments Inc.',
 'Goldman Sachs Group, Inc. (The)',
 'Halliburton Company',
 'Hartford Financial Services Gro',
 'Hasbro, Inc.',
 'HCA Healthcare, Inc.',
 'Healthpeak Properties, Inc.',
 'Henry Schein, Inc.',
 'The Hershey Company',
 'Hess Corporation',
 'Hewlett Packard Enterprise Comp',
 'Hilton Worldwide Holdings Inc.',
 'Hologic, Inc.',
 'Home Depot, Inc. (The)',
 'Honeywell International Inc.',
 'Hormel Foods Corporation',
 'Host Hotels',
 'Howmet Aerospace Inc.',
 'HP Inc.',
 'Humana Inc.',
 'Huntington Bancshares Incorpora',
 'Huntington Ingalls Industries, ',
 'International Business Machines',
 'IDEX Corporation',
 'IDEXX Laboratories, Inc.',
 'Illinois Tool Works Inc.',
 'Illumina, Inc.',
 'Incyte Corporation',
 'Ingersoll Rand Inc.',
 'Intel Corporation',
 'Intercontinental Exchange Inc.',
 'International Paper Company',
 'Interpublic Group of Companies,',
 'International Flavors & Fragran',
 'Intuit Inc.',
 'Intuitive Surgical, Inc.',
 'Invesco Ltd',
 'Invitation Homes Inc.',
 'IQVIA Holdings, Inc.',
 'Iron Mountain Incorporated (Del',
 'J.B. Hunt Transport Services, I',
 'Jack Henry & Associates, Inc.',
 'Jacobs Solutions Inc.',
 'Johnson & Johnson',
 'Johnson Controls International ',
 'JP Morgan Chase & Co.',
 'Juniper Networks, Inc.',
 'Kellogg Company',
 'Keurig Dr Pepper Inc.',
 'KeyCorp',
 'Keysight Technologies Inc.',
 'Kimberly-Clark Corporation',
 'Kimco Realty Corporation',
 'Kinder Morgan, Inc.',
 'KLA Corporation',
 'The Kraft Heinz Company',
 'Kroger Company (The)',
 'L3Harris Technologies, Inc.',
 'Laboratory Corporation of Ameri',
 'Lam Research Corporation',
 'Lamb Weston Holdings, Inc.',
 'Las Vegas Sands Corp.',
 'Leidos Holdings, Inc.',
 'Lennar Corporation',
 'Lincoln National Corporation',
 'Linde plc',
 'Live Nation Entertainment, Inc.',
 'LKQ Corporation',
 'Lockheed Martin Corporation',
 'Loews Corporation',
 "Lowe's Companies, Inc.",
 'Lumen Technologies, Inc.',
 'LyondellBasell Industries NV',
 'M&T Bank Corporation',
 'Marathon Oil Corporation',
 'Marathon Petroleum Corporation',
 'MarketAxess Holdings, Inc.',
 'Marriott International',
 'Marsh & McLennan Companies, Inc',
 'Martin Marietta Materials, Inc.',
 'Masco Corporation',
 'Mastercard Incorporated',
 'Match Group, Inc.',
 'McCormick & Company, Incorporat',
 "McDonald's Corporation",
 'McKesson Corporation',
 'Medtronic plc.',
 'Merck & Company, Inc.',
 'Meta Platforms, Inc.',
 'MetLife, Inc.',
 'Mettler-Toledo International, I',
 'MGM Resorts International',
 'Microchip Technology Incorporat',
 'Micron Technology, Inc.',
 'Microsoft Corporation',
 'Mid-America Apartment Communiti',
 'Moderna, Inc.',
 'Mohawk Industries, Inc.',
 'Molina Healthcare Inc',
 'Molson Coors Beverage Company',
 'Mondelez International, Inc.',
 'Monolithic Power Systems, Inc.',
 'Monster Beverage Corporation',
 "Moody's Corporation",
 'Morgan Stanley',
 'Mosaic Company (The)',
 'Motorola Solutions, Inc.',
 'MSCI Inc',
 'Nasdaq, Inc.',
 'NetApp, Inc.',
 'Netflix, Inc.',
 'Newell Brands Inc.',
 'Newmont Corporation',
 'News Corporation',
 'News Corporation',
 'NextEra Energy, Inc.',
 'Nike, Inc.',
 'NiSource Inc',
 'Nordson Corporation',
 'Norfolk Southern Corporation',
 'Northern Trust Corporation',
 'Northrop Grumman Corporation',
 'NortonLifeLock Inc.',
 'Norwegian Cruise Line Holdings ',
 'NRG Energy, Inc.',
 'Nucor Corporation',
 'NVIDIA Corporation',
 'NVR, Inc.',
 'NXP Semiconductors N.V.',
 "O'Reilly Automotive, Inc.",
 'Occidental Petroleum Corporatio',
 'Old Dominion Freight Line, Inc.',
 'Omnicom Group Inc.',
 'ON Semiconductor Corporation',
 'ONEOK, Inc.',
 'Oracle Corporation',
 'Organon & Co.',
 'Otis Worldwide Corporation',
 'PACCAR Inc.',
 'Packaging Corporation of Americ',
 'Paramount Global',
 'Parker-Hannifin Corporation',
 'Paychex, Inc.',
 'Paycom Software, Inc.',
 'PayPal Holdings, Inc.',
 'Pentair plc.',
 'Pepsico, Inc.',
 'PerkinElmer, Inc.',
 'Pfizer, Inc.',
 'Pacific Gas & Electric Co.',
 'Philip Morris International Inc',
 'Phillips 66',
 'Pinnacle West Capital Corporati',
 'Pioneer Natural Resources Compa',
 'PNC Financial Services Group, I',
 'Pool Corporation',
 'PPG Industries, Inc.',
 'PPL Corporation',
 'Principal Financial Group Inc',
 'Procter & Gamble Company (The)',
 'Progressive Corporation (The)',
 'Prologis, Inc.',
 'Prudential Financial, Inc.',
 'Public Service Enterprise Group',
 'PTC Inc.',
 'Public Storage',
 'PulteGroup, Inc.',
 'Qorvo, Inc.',
 'Quanta Services, Inc.',
 'QUALCOMM Incorporated',
 'Quest Diagnostics Incorporated',
 'Ralph Lauren Corporation',
 'Raymond James Financial, Inc.',
 'Raytheon Technologies Corporati',
 'Realty Income Corporation',
 'Regency Centers Corporation',
 'Regeneron Pharmaceuticals, Inc.',
 'Regions Financial Corporation',
 'Republic Services, Inc.',
 'ResMed Inc.',
 'Robert Half International Inc.',
 'Rockwell Automation, Inc.',
 'Rollins, Inc.',
 'Roper Technologies, Inc.',
 'Ross Stores, Inc.',
 'D/B/A Royal Caribbean Cruises L',
 'S&P Global Inc.',
 'Salesforce, Inc.',
 'SBA Communications Corporation',
 'Schlumberger N.V.',
 'Seagate Technology Holdings PLC',
 'Sealed Air Corporation',
 'DBA Sempra',
 'ServiceNow, Inc.',
 'Sherwin-Williams Company (The)',
 'Signature Bank',
 'Simon Property Group, Inc.',
 'Skyworks Solutions, Inc.',
 'J.M. Smucker Company (The) New',
 'Snap-On Incorporated',
 'SolarEdge Technologies, Inc.',
 'Southern Company (The)',
 'Southwest Airlines Company',
 'Stanley Black & Decker, Inc.',
 'Starbucks Corporation',
 'State Street Corporation',
 'STERIS plc (Ireland)',
 'Stryker Corporation',
 'SVB Financial Group',
 'Synchrony Financial',
 'Synopsys, Inc.',
 'Sysco Corporation',
 'T-Mobile US, Inc.',
 'T. Rowe Price Group, Inc.',
 'Take-Two Interactive Software, ',
 'Tapestry, Inc.',
 'Targa Resources, Inc.',
 'Target Corporation',
 'TE Connectivity Ltd. New Switze',
 'Teledyne Technologies Incorpora',
 'Teleflex Incorporated',
 'Teradyne, Inc.',
 'Tesla, Inc.',
 'Texas Instruments Incorporated',
 'Textron Inc.',
 'Thermo Fisher Scientific Inc',
 'TJX Companies, Inc. (The)',
 'Tractor Supply Company',
 'Trane Technologies plc',
 'Transdigm Group Incorporated',
 'The Travelers Companies, Inc.',
 'Trimble Inc.',
 'Truist Financial Corporation',
 'Twitter, Inc.',
 'Tyler Technologies, Inc.',
 'Tyson Foods, Inc.',
 'U.S. Bancorp',
 'UDR, Inc.',
 'Ulta Beauty, Inc.',
 'Union Pacific Corporation',
 'United Airlines Holdings, Inc.',
 'United Parcel Service, Inc.',
 'United Rentals, Inc.',
 'UnitedHealth Group Incorporated',
 'Universal Health Services, Inc.',
 'Valero Energy Corporation',
 'Ventas, Inc.',
 'VeriSign, Inc.',
 'Verisk Analytics, Inc.',
 'Verizon Communications Inc.',
 'Vertex Pharmaceuticals Incorpor',
 'V.F. Corporation',
 'Viatris Inc.',
 'VICI Properties Inc.',
 'Visa Inc.',
 'Vornado Realty Trust',
 'Vulcan Materials Company (Holdi',
 'Westinghouse Air Brake Technolo',
 'Walgreens Boots Alliance, Inc.',
 'Walmart Inc.',
 'Warner Bros. Discovery, Inc. - ',
 'Waste Management, Inc.',
 'Waters Corporation',
 'WEC Energy Group, Inc.',
 'Wells Fargo & Company',
 'Welltower Inc.',
 'West Pharmaceutical Services, I',
 'Western Digital Corporation',
 'Westrock Company',
 'Weyerhaeuser Company',
 'Whirlpool Corporation',
 'Williams Companies, Inc. (The)',
 'Willis Towers Watson Public Lim',
 'W.W. Grainger, Inc.',
 'Wynn Resorts, Limited',
 'Xcel Energy Inc.',
 'Xylem Inc.',
 'Yum! Brands, Inc.',
 'Zebra Technologies Corporation',
 'Zimmer Biomet Holdings, Inc.',
 'Zions Bancorporation N.A.',
 'Zoetis Inc.']